name: Java CI with Gradle

on:
  - push
  - workflow_dispatch

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: RunGatling
      run: ./gradlew gatlingRun
    - name: Upload test failure report
      uses: actions/upload-artifact@v2
      with:
        name: reports
        path: lib/build/reports/gatling
        retention-days: 3
